### ISSUE TITLE
Erros while "Make" the source code

### ISSUE THREAD

**Issue by jonimessi** [perfsonar/bwctl#40]
Get the following warnings while execute "Make"-command:
bwctl.c:1934:26: warning: format specifies type 'unsigned long' but the argument has type 'int' [-Wformat]
                         MSS_MIN, MSS_MAX);
                         ^~~~~~~
bwctl.c:1926:28: note: expanded from macro 'MSS_MIN'
#           define MSS_MIN (28)
                           ^~~~
bwctl.c:1934:35: warning: format specifies type 'unsigned long' but the argument has type 'int' [-Wformat]
                         MSS_MIN, MSS_MAX);
                                  ^~~~~~~
bwctl.c:1927:28: note: expanded from macro 'MSS_MAX'
#           define MSS_MAX (9 * 1024)
                           ^~~~~~~~~~

When I want to use bwctl -m ... the command does not work. It return error:
iperf3: error - unable to set TCP/SCTP MSS: Invalid argument
bwctl: local tool exited before expected with status=1

Is it possible that the error depend on the Warnings in the make-command?

Using bwctl Version 1.6.2-1
Running on FreeBSD 10.3
iperf3 Version 3.1.6

**Comment by mfeit-internet2** [comment]
The warning in BWCTL is in [a `printf()` called when the MSS value is invalid](https://github.com/perfsonar/bwctl/blob/0ab55aca2d7bcbcac0123fe6f60d0b1c0cd85c00/bwctl/bwctl.c#L1932).  It's harmless, but we'll try to get rid of it.

The error you're seeing at runtime came from iperf3, which is maintained by ESNet.  I don't believe FreeBSD is one of the supported platforms, which may not be capable of setting MSS.
