### ISSUE TITLE
Connection Refused in BWCTL when iperf3 got upgraded from 3.3-1 to 3.5-1

### ISSUE THREAD

**Issue by John-McClane** [perfsonar/bwctl#43]
Context
Version of bwctl: bwctl1.6.5-1
Hardware: ESX Virtual Machine
Operating system (and distribution, if any): Linux 4.14.0-3-amd64 #1 SMP Debian 4.14.17-1 (2018-02-14) x86_64 GNU/Linux
Other relevant information: bwctl 1.6.5-1, iperf3 3.5-1, libiperf0 3.5-1

Bug Report
I'm running some tests for about a month now from my VM to a particular testpoint in Lookup Service Directory [http://stats.es.net/ServicesDirectory/](url).
The testpoint is [http://stats.es.net/ServicesDirectory/#uri=lookup%2Fservice%2F642e2fcd-988e-4198-bf97-1a6edf6ef171](url) 
in INFN-NAPOLI-ATLAS BWCTL Server, perfsonar2.na.infn.it , INFN-NAPOLI-ATLAS, Napoli, Italy.

Not that it really matters, because I can't get ANY BWCTL measurements from and to ANY testpoints.

Up till 14/03/2018 BWCTL and everything else was working fine from and to ANY testpoint:
  `SENDER START
Connecting to host 90.147.67.252, port 5550
[ 16] local xxx.xxx.xxx.xxx port 48427 connected to 90.147.67.252 port 5550
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[ 16]   0.00-1.00   sec  70.5 MBytes   591 Mbits/sec   18   2.44 MBytes       (omitted)
[ 16]   1.00-2.00   sec  60.0 MBytes   503 Mbits/sec    0   2.47 MBytes       (omitted)
[ 16]   2.00-3.00   sec  60.0 MBytes   503 Mbits/sec    0   2.58 MBytes       (omitted)
[ 16]   3.00-4.00   sec  66.2 MBytes   556 Mbits/sec    0   2.83 MBytes       (omitted)
[ 16]   0.00-1.00   sec  71.2 MBytes   598 Mbits/sec    0   3.21 MBytes
[ 16]   1.00-2.00   sec  85.0 MBytes   713 Mbits/sec    0   3.75 MBytes
[ 16]   2.00-3.00   sec  98.8 MBytes   828 Mbits/sec    0   4.45 MBytes
[ 16]   3.00-4.00   sec  75.0 MBytes   629 Mbits/sec    5   2.37 MBytes
[ 16]   4.00-5.00   sec  57.5 MBytes   482 Mbits/sec    0   2.41 MBytes
[ 16]   5.00-6.00   sec  58.8 MBytes   493 Mbits/sec    0   2.56 MBytes
[ 16]   6.00-7.00   sec  65.0 MBytes   545 Mbits/sec    0   2.84 MBytes
[ 16]   7.00-8.00   sec  72.5 MBytes   608 Mbits/sec    0   3.27 MBytes
[ 16]   8.00-9.00   sec  85.0 MBytes   713 Mbits/sec    0   3.85 MBytes
[ 16]   9.00-10.00  sec  87.5 MBytes   734 Mbits/sec    2   3.32 MBytes
[ 16]  10.00-11.00  sec  80.0 MBytes   671 Mbits/sec    0   3.34 MBytes
[ 16]  11.00-12.00  sec  80.0 MBytes   671 Mbits/sec    0   3.39 MBytes
[ 16]  12.00-13.00  sec  83.8 MBytes   703 Mbits/sec    0   3.50 MBytes
[ 16]  13.00-14.00  sec  86.2 MBytes   724 Mbits/sec    0   3.67 MBytes
[ 16]  14.00-15.00  sec  91.2 MBytes   765 Mbits/sec    0   3.90 MBytes
[ 16]  15.00-16.00  sec  92.5 MBytes   776 Mbits/sec   16   2.63 MBytes
[ 16]  16.00-17.00  sec  63.8 MBytes   535 Mbits/sec    0   2.64 MBytes
[ 16]  17.00-18.00  sec  63.8 MBytes   535 Mbits/sec    0   2.67 MBytes
[ 16]  18.00-19.00  sec  65.0 MBytes   545 Mbits/sec    0   2.75 MBytes
[ 16]  19.00-20.00  sec  67.5 MBytes   566 Mbits/sec    0   2.90 MBytes
[ 16]  20.00-21.00  sec  72.5 MBytes   608 Mbits/sec    0   3.10 MBytes
[ 16]  21.00-22.00  sec  78.8 MBytes   661 Mbits/sec    0   3.37 MBytes
[ 16]  22.00-23.00  sec  85.0 MBytes   713 Mbits/sec    0   3.71 MBytes
[ 16]  23.00-24.00  sec  95.0 MBytes   797 Mbits/sec    0   4.12 MBytes
[ 16]  24.00-25.00  sec   106 MBytes   891 Mbits/sec    0   4.59 MBytes
[ 16]  25.00-26.00  sec  90.0 MBytes   755 Mbits/sec    3   3.68 MBytes
[ 16]  26.00-27.00  sec  90.0 MBytes   755 Mbits/sec    0   3.70 MBytes
[ 16]  27.00-28.00  sec  91.2 MBytes   765 Mbits/sec    0   3.78 MBytes
[ 16]  28.00-29.00  sec  93.8 MBytes   786 Mbits/sec    0   3.92 MBytes
[ 16]  29.00-30.00  sec  97.5 MBytes   818 Mbits/sec    0   4.12 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[ 16]   0.00-30.00  sec  2.37 GBytes   679 Mbits/sec   26             sender
[ 16]   0.00-30.04  sec  2.38 GBytes   680 Mbits/sec                  receiver

iperf Done.

SENDER END
`

The problem started at 14/03/2018, and after examining the logs I think I found the culprit, after an apt-get update:
`Preparing to unpack .../10-libiperf0_3.5-1_amd64.deb ...
Unpacking libiperf0 (3.5-1) over (3.3-1) ...
Preparing to unpack .../11-iperf3_3.5-1_amd64.deb ...
Unpacking iperf3 (3.5-1) over (3.3-1) ...
`

After the iperf3, libiperf0 update all I'm getting is this:
`bwctl: Requested tools supporting the requested options not available by both servers. See the '-T' option
bwctl: Available tools that support the requested options: iperf nuttcp`

I have tried to rollback the iperf3, libiperf0, I have purged bwctl and iperf3, libiperf0, reinstalled them, but nothing seems to be working.
I have built bwctl and iperf3, libiperf0 from source and still nothing.
The end result from each attempt is the "requested tools not supported".

Even if I try to establish an iperf3 connection I get:
`iperf3` -t 10 -O 4 -c 90.147.67.252
iperf3: error - unable to connect to server: Connection `refused`

The version of the tools are as follows:
`
apt-get install bwctl-server bwctl-client iperf3 libiperf0
bwctl-client is already the newest version (1.6.5-1).
bwctl-server is already the newest version (1.6.5-1).
iperf3 is already the newest version (3.5-1).
libiperf0 is already the newest version `(3.5-1).`

Although, as a side note, `bwctl` `-V` shows `Version:` `1.6.5-1`
but `iperf3` `-v` shows `iperf` 3.4 (cJSON `1.5.2)`.

Any thoughts?
I have tried anything I could think of for the past three days, and nothing seems to be working.
Any help would be greatly appreciated.
Thanks in advance.

**Comment by arlake228** [comment]
There is a hard-wired check in BWCTL for the iperf3 version. We didn't bump that when iperf3 got new packages a couple days ago. Just committed a fix for that and will be uploading packages in the next day for supported CentOS and Debian versions in next day or two. Thanks for reporting.

**Comment by John-McClane** [comment]
Looking forward to testing the updated version.
Thanks for your help.

**Comment by laeti-tia** [comment]
Debian packages for 1.6.6 are now available in our repositories.

**Comment by John-McClane** [comment]
Wow, talking about prompt response.

bwctl v1.6.6-1 on Debian is humming along joyfully,
from the moment you made it available on the repo up till now
(and hopefully for the foreseeable future).

Thanks a lot, indeed.
Keep up the excellent work.
