### ISSUE TITLE
deterministic scheduling of tests

### ISSUE THREAD

**Issue by arlake228** [perfsonar/bwctl#7]
_From @arlake228 on March 14, 2015 12:21_

Original [issue 925](https://code.google.com/p/perfsonar-ps/issues/detail?id=925) created by arlake228 on 2014-06-11T13:34:56.000Z:

Instead of specifying a particular interval such as every 4 hours, being able to specify using a cron-like method to run tests at specific times. An example might be to run a test every other hour on Mon, Wedn, Fri. Implementing this would likely require the authenticated user enhancement outline in issue 924 because these tests would need to pre-empt existing tests to get as close to their scheduled time as possible.

The most straightforward implementation of this would likely be to include something akin to the standard way cron entries are described, such as:

0 0 \* \* 5

would schedule a test to be run every Friday at exactly midnight.

_Copied from original issue: perfsonar/project#923_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=925#c1) originally posted by arlake228 on 2015-01-27T14:49:27.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=925#c2) originally posted by arlake228 on 2015-01-30T19:50:16.000Z:

Issue 875 has been merged into this issue.

**Comment by mfeit-internet2** [comment]
There might be some useful nuggets to be had this implementation:  https://code.google.com/p/ncrontab/
